language: java
script: mvn clean install
jdk:
  - openjdk8
before_install:
    - wget -P /home/travis/build/GrangerTheDog/TCJukebox/lib  -O MCJukebox.jar https://glare.now.sh/oliverdunk/JukeboxAPI/jar
