name: TCJukebox
version: 1.1-SNAPSHOT
description: "TCJukebox adds MCJukebox audio to Trains"
main: nl.grangerthedog.tcjukebox.Main
api-version: 1.15
authors: ["Melerpe"]
depend: [MCJukebox, BKCommonLib, Train_Carts]
